name: flutter_password_input
description: A customizable password text field widget with Caps Lock detection,
  visibility toggle, force English input mode, and comprehensive theming support.
version: 0.3.4
homepage: https://github.com/kihyun1998/flutter_password_input
repository: https://github.com/kihyun1998/flutter_password_input
issue_tracker: https://github.com/kihyun1998/flutter_password_input/issues

topics:
  - password
  - textfield
  - input
  - caps-lock
  - security

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_ime: ^2.1.3
  just_tooltip: ^0.2.3

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
